---
name: Code Vulnerability Test
description: Set up environment, run code vulnerability checks, and report
  findings.

inputs:
  os:
    default: ubuntu-latest
    description: The operating system to use
    required: false
  python_version:
    default: "3.12"
    description: The version of Python to use
    required: false
  poetry_install_options:
    default: "--only=vulnerability --no-root"
    description: Options for installing dependencies via poetry
    required: false
  poetry_export_options:
    default: "--only=vulnerability"
    description: Options for exporting dependencies for cache invalidation
    required: false
  config_path:
    description: The path to the Bandit configuration file
    default: "pyproject.toml"
    required: false
  file_path:
    description: The path to the file or directory to check for vulnerabilities
    required: true

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up environment
      uses: elixir-cloud-aai/actions/python/setup/poetry@main
      with:
        os: ${{ inputs.os }}
        python_version: ${{ inputs.python_version }}
        poetry_install_options: ${{ inputs.poetry_install_options }}
        poetry_export_options: ${{ inputs.poetry_export_options }}

    - name: Check code vulnerabilities with Bandit
      shell: bash
      run: poetry run bandit \
        -c ${{ inputs.config_path }} \
        -r ${{ inputs.file_path }}
...
