---
name: Semantic PR Check
description: Checks if the PR title follows semantic guidelines.

inputs:
  github_token:
    description: The GitHub token to use for authentication
    required: true
  pr_title:
    description: The title of the pull request
    required: true

runs:
  using: composite
  steps:
    - name: Check if the PR title is semantic
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        types: |
          fix
          feat
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        subjectPattern: ^(?![A-Z])(?=.{1,50}$).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character & not have more than 50
          characters.

    - name: Check length of PR title
      shell: bash
      run: |
        PR_TITLE="${{ inputs.pr_title }}"
        if [ ${#PR_TITLE} -gt 50 ]; then
          echo "The PR title is too long. Please keep it under 50 characters."
          exit 1
        fi
...
