---
name: Type Check
description: Runs a type check on the codebase to ensure type safety and
  correctness.

inputs:
  python_version:
    description: Python version to use
    default: "3.12"
    required: false
  poetry_install_options:
    description: Options for installing dependencies via poetry
    required: false
    default: "--with=code_quality --with=types --no-root"
  poetry_export_options:
    description: Options for exporting dependencies to check for hash
      changes for cache invalidation
    required: false
    default: "--with=code_quality --with=types"
  file_path:
    description: The path to the file or directory to type check
    required: false
    default: " . "


runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up environment
      uses: elixir-cloud-aai/actions/python/setup/poetry@main
      with:
        python_version: ${{ inputs.python_version }}
        poetry_install_options: ${{ inputs.poetry_install_options }}
        poetry_export_options: ${{ inputs.poetry_export_options }}

    - name: Check types
      shell: bash
      run: poetry run mypy ${{ inputs.file_path }}
...
